/**
 * @fileoverview
 * This file is auto-generated by the 'scripts/generate-image-list.js' script.
 * Do not edit this file manually. All changes will be overwritten.
 */

export const imageList = {
  imgOnboard: require('./img-onboard.png'),
  imgSplash: require('./img-splash.png'),
};
